### ISSUE TITLE
the examples on the code page fail

### ISSUE THREAD

**Issue by monetschemist** [geoscript/geoscript-groovy#28]
Just trying geoscript-groovy for the first time, and the second and third examples on the code page are failing for me.

The second example has a typo in it as well.  The line

    def p2 = Projection.transform(p, "EPSG:4326", "EPSG:26912")

should read

    def p2 = Projection.transform(p1, "EPSG:4326", "EPSG:26912")

When I fix the typo and run it with geoscript-groovy, this is the output I get:

Mar 11, 2016 3:41:21 PM org.geotools.factory.FactoryRegistry scanForPlugins
WARNING: Can't load a service for category "MathTransformProvider". Cause is "ServiceConfigurationError: org.geotools.referencing.operation.MathTransformProvider: Provider org.geotools.referencing.operation.transform.WarpTransform2D$Provider could not be instantiated".
java.util.ServiceConfigurationError: org.geotools.referencing.operation.MathTransformProvider: Provider org.geotools.referencing.operation.transform.WarpTransform2D$Provider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)

(rest of lines removed for brevity's sake).

A similar problem occurs with the third example.

This is with groovy 2.4.6 (the latest as of today) and GeoScript 1.6.0 (also the latest).

Please help!

**Comment by jericks** [comment]
Thanks for reporting the documentation error.  I pushed up a fix.  

As for the error, I think you need to install Java Advanced Imaging:

http://osgeo-org.1560.x6.nabble.com/Help-with-an-error-td4329334.html

**Comment by monetschemist** [comment]
Thanks, Jared!  I'll give that a try and report back.

On Sat, Mar 12, 2016 at 12:40 AM, Jared Erickson <notifications@github.com>
wrote:

> Thanks for reporting the documentation error. I pushed up a fix.
>
> As for the error, I think you need to install Java Advanced Imaging:
>
> http://osgeo-org.1560.x6.nabble.com/Help-with-an-error-td4329334.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoscript/geoscript-groovy/issues/28#issuecomment-195651477>
> .
>



-- 
Chris Hermansen · clhermansen "at" gmail "dot" com

C'est ma façon de parler.

**Comment by monetschemist** [comment]
Good afternoon, Jared,

I have looked around for the files mentioned on the link you sent.  The
jai.java.net links on that page no longer work.  The  Oracle links arrive
at a summary page (ie not at the product itself).

The jai and imaging files can be found elsewhere on the Oracle site
http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-java-client-419417.html
but only provide 32-bit versions.

There are some forked bits on github.  But not sure about them.

I searched on google for jai-1_1_3-lib-linux-amd64 and found this link:
http://data.opengeo.org/suite/jai/

I was able to download the two shell installer scripts for amd64 found
there.  The jai seemed to install correctly, but the jai-imageio install
process ended with:

Unpacking...
> tail: cannot open ‘+215’ for reading: No such file or directory
> Checksumming...
> 1
> The download file appears to be corrupted.  Please refer
> to the Troubleshooting section of the Installation
> Instructions on the download page for more information.
> Please do not attempt to install this archive file.
>

which doesn't give me a great amount of confidence.  But this post
http://idoimaging.com/wiki/tiki-index.php?page=Java+Advanced+Imaging
explains how to fix that (and incidently gives a good overview of
installing all the stuff).

So; with all of that, now the second and third scripts work.

By the way I have since discovered that the jai library is available in the
Ubuntu repositories, but not the jai-imageio library.



On Sat, Mar 12, 2016 at 12:40 AM, Jared Erickson <notifications@github.com>
wrote:

> Thanks for reporting the documentation error. I pushed up a fix.
>
> As for the error, I think you need to install Java Advanced Imaging:
>
> http://osgeo-org.1560.x6.nabble.com/Help-with-an-error-td4329334.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoscript/geoscript-groovy/issues/28#issuecomment-195651477>
> .
>



-- 
Chris Hermansen · clhermansen "at" gmail "dot" com

C'est ma façon de parler.

**Comment by jericks** [comment]
Nice job!  We should really add some docs to the README.  Do you want to put together a pull request?

I found the GeoTools Docs for JAI and ImageIO:
http://docs.geotools.org/latest/userguide/build/install/jdk.html

Would that have helped?

**Comment by monetschemist** [comment]
Jared, sorry to be slow on this.

I've got a crazy busy Monday and Tuesday but let me look at this and I'll
put a draft together.  Then if you like it we can put it in the README.

On Sat, Mar 12, 2016 at 6:03 PM, Jared Erickson <notifications@github.com>
wrote:

> Nice job! We should really add some docs to the README. Do you want to put
> together a pull request?
>
> I found the GeoTools Docs for JAI and ImageIO:
> http://docs.geotools.org/latest/userguide/build/install/jdk.html
>
> Would that have helped?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoscript/geoscript-groovy/issues/28#issuecomment-195808641>
> .
>



-- 
Chris Hermansen · clhermansen "at" gmail "dot" com

C'est ma façon de parler.

**Comment by monetschemist** [comment]
Jared, I have a bit of time to pull this together into the documentation.  Having said that, I'm not sure how to proceed.  Can you offer me a few more hints as to what I should do?

**Comment by jericks** [comment]
How about a pull request mentioning that Java ImageIO and Java Advanced Imaging are required in the Usage section of the README.rst?  We should also link to the GeoTools JAI and ImageIO install guide (http://docs.geotools.org/latest/userguide/build/install/jdk.html).

https://github.com/geoscript/geoscript-groovy/blob/master/README.rst#use

Jared
